const ShopActionTypes = {
    UPDATE_PRODUCTS: 'UPDATE_PRODUCTS',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    TOGGLE_PRODUCT: 'TOGGLE_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT'
};

export default ShopActionTypes;
