export const StockActionTypes = {
    UPDATE_STOCK: 'UPDATE_STOCK',
    ADD_STOCK_ITEM: 'ADD_STOCK_ITEM',
    SET_STOCK_ITEM_QTTY: 'SET_STOCK_ITEM_QTTY',
    DEC_STOCK_ITEM_QTTY: 'DEC_STOCK_ITEM_QTTY',
    SET_STOCK_ITEM_QTTY_ALARM: 'SET_STOCK_ITEM_QTTY_ALARM',
    SAVE_STOCK_ITEMS: 'SAVE_STOCK_ITEMS'
}